name: Python lint and test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src
    - name: Test with pytest
      run: |
        python -m pytest --cov=src src/test
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        token: 6a3b0dae-20fc-4121-837e-dc4d640e4947
        files: .coverage
        flags: unittests
        verbose: true